### ISSUE TITLE
Project license?

### ISSUE THREAD

**Issue by bsinky** [trekawek/coffee-gb#1]
I've really been enjoying looking through coffee-gb's code recently.  It's been a huge help in drawing inspiration for a Game Boy emulator that I'm currently working on, as the documents linked in the README are great, and your own code is very understandable.

**What I'm wondering is, is coffee-gb's source code released under any particular license?**

Whatever the answer, thanks for your work on this project!

**Comment by trekawek** [comment]
Hi @bsinky!

Thanks for the nice words. I've added the LICENSE file: 513323e, it's the MIT one.

Regards,
Tomek
