### ISSUE TITLE
Performance is bad and audio making popping noises (audio is also stuttery)

### ISSUE THREAD

**Issue by Mario3264** [trekawek/coffee-gb#10]
It runs slowly but sometimes it speeds up and audio is stuttery, causing popping noises. Also, I think there should be a input GUI to assign controls to the keyboard, though the default key layout isn't too bad.
EDIT: The games run better now but it still has problems, GB games run better than GBC games as there is some stuttering in framerate.

**Comment by Mario3264** [comment]
No replies for a while so I decided to close.

**Comment by Johnny850807** [comment]
It's yet an issue, hope it getting improved :), great codes!
