### ISSUE TITLE
Embedded Emulator Help

### ISSUE THREAD

**Issue by ChefFloyardee** [trekawek/coffee-gb#12]
Hi there!

I currently host a ROM Hack on my website using an embedded flash emulator, but since Chrome is going to discontinue flash soon I am looking for a Java/other type of embedded emulator to replace it with.

I found your Java GB, and I was wondering if this would work for me. If so, could you help me set it up?

Thanks and let me know :D

**Comment by trekawek** [comment]
Closing as stale.
