### ISSUE TITLE
How do i save my games

### ISSUE THREAD

**Issue by FinnStolze** [trekawek/coffee-gb#13]
Hey trekawek,
nice work with your gb-emulator. I would love to play some games with it.

Is ther a feature to save my games or open the .sav games again.

Thanks in advance,
Finn

**Comment by LoneDev6** [comment]
Depends on the game.
For example in Pokemon you save using the start menu and when you relaunch the game you see the "continue" button automatically

**Comment by trekawek** [comment]
The emulator only support battery saves. So the game needs to allow saving and then you should use game-specific options to do it.
