### ISSUE TITLE
Severe frame skip issues

### ISSUE THREAD

**Issue by orange451** [trekawek/coffee-gb#16]
Not sure why this is happening. The emulator runs (sometimes) at full fps, and sometimes at a severely reduced FPS. Sometimes I only get 1-2 frames per second, with obnoxious beeping sounds because the audio can't smoothly play.

I am running Super Mario Bros Deluxe rom with Oracle JDK 8

**Comment by trekawek** [comment]
There was a series of optimization commits today, hopefully it'll make it better.
