### ISSUE TITLE
Remove SLF4J-Simple binding

### ISSUE THREAD

**Issue by Zabuzard** [trekawek/coffee-gb#19]
https://github.com/trekawek/coffee-gb/blob/9f2ea204f8a49cdaf3adff05b58e144b11b07f04/pom.xml#L110-L113

Please remove any concrete SLF4J bindings, such as **slf4j-simple** from your dependencies. This makes it hard for users of your project to define their own binding, such as log4j2 or similar:

![error](https://i.imgur.com/Fh6wMtK.png)

This is mainly a problem because your artifacts are fat/uber-jars. So dependency-exclusions dont work. Ideally, a library would never include any concrete bindings but only the facade itself.

Cheers and thanks for this awesome project!

**Comment by trekawek** [comment]
Thanks for the suggestion @Zabuzard! Could you take a look at #21 to see if it makes it better?

**Comment by Zabuzard** [comment]
Good stuff, thanks 👍

**Comment by trekawek** [comment]
Version with removed binding has been released as 1.0.2.
