### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by Luraktinus** [trekawek/coffee-gb#2]
hey, i am not into java that much but i need to build this, can you add how i could build this? Thanks

**Comment by trekawek** [comment]
@Luraktinus - it can be built with [Maven](https://maven.apache.org/), I've added the appropriate section to the README.md. I'm glad you're interested in the emulator - could you share your use case?

**Comment by Luraktinus** [comment]
i want to get an emulator on my RaspberryPi3 running, i am using it as a Desktop pc mostly but the range of working emulators is limited.
So i wanted to try this one.

**Comment by trekawek** [comment]
Got it. Maybe it's a good time to make an official release :) The output jar can be found here:

https://github.com/trekawek/coffee-gb/releases/tag/coffee-gb-1.0.0

**Comment by Luraktinus** [comment]
thanks, that solves some problems
