### ISSUE TITLE
How to open

### ISSUE THREAD

**Issue by DatEmulatorDude** [trekawek/coffee-gb#3]
I came across this developing my own emulator, and gave this a try, but how exactly do you open this?

**Comment by trekawek** [comment]
Hi @DatEmulatorDude!

Please download the [most recent release](https://github.com/trekawek/coffee-gb/releases/download/coffee-gb-1.0.0/coffee-gb-1.0.0.jar), and use the command line to launch it, passing the ROM path as a single argument, eg.:

```
java -jar coffee-gb-1.0.0.jar marioland.gb
```
