### ISSUE TITLE
Add Title for macOS bar

### ISSUE THREAD

**Issue by carstenhag** [trekawek/coffee-gb#5]
I don't know how that bar is called, anyway, you could add the program name there.

<img width="137" alt="bildschirmfoto 2018-05-23 um 21 48 30" src="https://user-images.githubusercontent.com/3776997/40447501-176baebc-5ed3-11e8-80c2-102a7febeb9f.png">

**Comment by trekawek** [comment]
Fixed. Thanks for noticing this!
