### ISSUE TITLE
Map y to "z" for qwertz users

### ISSUE THREAD

**Issue by carstenhag** [trekawek/coffee-gb#6]
Basically, at the bottom keyboard row I have y x c   and not z x c like you.

I would have to put my hands in a weird position if y isn't mapped to z too.

**Comment by trekawek** [comment]
The default key bindings can be now changed with the `~/.coffeegb.properties` file. Its format is described in the [README.md](https://github.com/trekawek/coffee-gb/blob/master/README.md#key-bindings).
