### ISSUE TITLE
Stereo audio is flipped

### ISSUE THREAD

**Issue by dylmeadows** [trekawek/coffee-gb#8]
Discovered playing Pokemon Crystal. If you set the sound to stereo in the game options the left and right side are flipped. Easily noticeable during a Pokemon battle during attacks.

**Comment by trekawek** [comment]
Thanks for the report! It should be fixed by the commit f39cd4d.

**Comment by dylmeadows** [comment]
Just checked it and can confirm that it's fixed! Thanks for the quick response!
