### ISSUE TITLE
Run emulator on 178×128 pixel Monochrome LCD

### ISSUE THREAD

**Issue by jabrena** [trekawek/coffee-gb#9]
Hi, I would like to know it the project could run in this kind of display:

178×128 pixel
Monochrome LCD

The display is part of Lego Mindstorms:
https://www.lego.com/es-ar/mindstorms/products/mindstorms-ev3-31313

![](https://www.lego.com/r/www/r/mindstorms/-/media/franchises/mindstorms%202014/products/in%20the%20box/inthebox_45500_p_brik_left_square.png?l.r2=243968022)

The brick run debian and openjdk10

What do you think?

Cheers

Juan Antonio

**Comment by trekawek** [comment]
Hi @jabrena,

while the brick should provide enough computing power to run the emulator, the display doesn't seem to be sufficient. Gameboy have a 160x144 display (which is more or less what the brick can offer), but also 4 colors (or brightness levels) while the brick display is black and white.

**Comment by jabrena** [comment]
What is the most simple game in Gameboy that I could test the emulator with 2 Colors?

In Debian Stretch, the Display driver changed and maybe it could be possible to manage that requirement: 4 colors (or brightness levels)

Juan Antonio

**Comment by trekawek** [comment]
Hi @jabrena,

I think all the games uses 4 colors, even the simplest one, eg. Tetris.

The Coffee GB won't work on EV3 out of the box. It uses the Java Swing library to display the GB screen in a window, while for the Lego brick it'd require a custom graphics driver to talk to the LCD.

**Comment by jabrena** [comment]
Mmmm, maybe you have reason. :(

Thanks for the comment.

Cheers

Juan Antonio

**Comment by Lukas1h** [comment]
https://github.com/ev3dev/ev3dev/issues/729#issuecomment-384465619
